//
//  QuestionCatagories.swift
//  inVISABLE
//
//  Created by Samantha Konigsberg on 6/14/17.
//  Copyright © 2017 Samantha Konigsberg. All rights reserved.
//

import Foundation


let illnesses = [
                "Acanthamoeba Keratitis",
                "Achalasia",
                "Achondroplasia",
                "Acute Disseminated Encephalomyelitis",
                "Addison's Disease",
                "Adenoid Cystic Carcinoma",
                "ADHD/ADD",
                "Adie's Pupil",
                "Adrenal Cancer",
                "Adrenal Insufficiency",
                "Adrenoleukodystrophy",
                "Agammaglobulinemia",
                "Agenesis of the Corpus Callosum",
                "Aicardi Syndrome",
                "Aicardi-Goutieres Syndrome Disorder",
                "Alagille Syndrome",
                "Alexander Disease",
                "Allan-Herndon-Dudley Syndrome",
                "Alopecia Areata",
                "Alpha-1 Antitrypsin Deficiency",
                "ALS (Lou Gehrig's Disease)",
                "Alternating Hemiplegia",
                "Alzheimer's Disease",
                "Amniotic Band Syndrome",
                "Anaphylaxis",
                "Anencephaly",
                "Angelman Syndrome",
                "Ankylosing Spondylitis",
                "Anorexia",
                "Antiphospholipid Syndrome",
                "Anxiety",
                "Apert Syndrome",
                "Aphantasia",
                "Aphasia",
                "Apraxia",
                "Arachnoiditis",
                "Arnold-Chiari Malformation",
                "Arthritis",
                "Arthrogryposis",
                "Arthrogryposis Multiplex Congenita",
                "Asperger's Syndrome",
                "Asthma",
                "Ataxia",
                "Auditory Processing Disorder",
                "Autism Spectrum Disorder",
                "Autoimmune Autonomic Ganglionopathy",
                "Autoimmune Hepatitis",
                "Autoimmune Thyroid Disease",
                "Autonomic Dysfunction",
                "Autonomic Dysreflexia",
                "Avascular Necrosis",
                "Babesiosis",
                "Bardet-Biedl Syndrome",
                "Barth Syndrome",
                "Batten Disease",
                "Beckwith-Wiedemann Syndrome",
                "Behcet's Disease",
                "Benign Intracranial Hypertension",
                "Biliary Atresia",
                "Bipolar Disorder",
                "Blindness",
                "Blood Cancer",
                "Blount's Disease",
                "Bohring-Opitz Syndrome",
                "Bone Cancer",
                "Borderline Personality Disorder",
                "Brain Tumor",
                "Breast Cancer",
                "Bronchiectasis",
                "Brown-Vialetto-Van Laere Syndrome",
                "Bulimia",
                "Canavan Disease",
                "Cancer",
                "Cantú Syndrome",
                "Cardiofaciocutaneous Syndrome",
                "Cardiomyopathy",
                "Carpal Tunnel Syndrome",
                "Caudal Regression Syndrome",
                "Cavernomas",
                "Cavernous Angioma",
                "Celiac Disease" ,
                "Central Core Disease",
                "Central Sensitization Syndrome",
                "Cerebellar Degeneration",
                "Cerebellar Vestibular Disorder",
                "Cerebral Palsy",
                "Cerebrocostomandibular Syndrome",
                "Cervical Cancer",
                "Charcot-Marie-Tooth Disease" ,
                "CHARGE Syndrome",
                "Chiari Malformation",
                "Chromosome 12, Microdeletion",
                "Chronic Inflammatory Demyelinating Polyneuropathy (CIDP)",
                "Chronic Inflammatory Response Syndrome (CIRS)",
                "Chronic Lung Disease",
                "Chronic Obstructive Pulmonary Disease (COPD)",
                "Chronic Pain",
                "Chronic Pancreatitis",
                "Chronic Traumatic Encephalopathy",
                "Chronic Vestibular Migraine",
                "Citrullinemia",
                "CLOVES Syndrome",
                "Coffin-Siris Syndrome",
                "Colon Cancer",
                "Color Blindness",
                "Colorectal Cancer",
                "Common Variable Immune Deficiency",
                "Complex Regional Pain Syndrome",
                "Congenital Adrenal Hyperplasia",
                "Congenital Central Hypoventilation Syndrome",
                "Congenital Diaphragmatic Hernia",
                "Congenital Dyserythropoietic Anemia",
                "Congenital Generalized Lipodystrophy",
                "Congenital Heart Defect/Disease",
                "Congenital Vascular Cavernous Malformations",
                "Congestive Heart Failure",
                "Conradi-Hunermann Syndrome",
                "Cornelia de Lange Syndrome",
                "Costello Syndrome",
                "Craniosynostosis",
                "Cri du Chat Syndrome",
                "Crohn's Disease",
                "Crouzon Syndrome",
                "CSF Leak (Spinal)",
                "Cushing's Syndrome",
                "Cyclic Vomiting Syndrome",
                "Cyclothymic Disorder",
                "Cystic Fibrosis",
                "Cystinosis",
                "Dandy-Walker Syndrome",
                "De Quervain's Tenosynovitis",
                "Deafness",
                "Degenerative Disc Disease",
                "Dementia",
                "Depression",
                "Dercum's Disease (Adiposis Dolorosa)",
                "Dermatillomania",
                "Dermatomyositis",
                "Diabetes",
                "Diabetes Type 1",
                "Diabetic Neuropathy",
                "Diamond Blackfan Anemia",
                "DiGeorge Syndrome",
                "Disability",
                "Down Syndrome",
                "Dravet Syndrome",
                "Duchenne Muscular Dystrophy",
                "Dup 15q Syndrome",
                "Dwarfism",
                "Dysautonomia",
                "Dyscalculia",
                "Dysferlinopathy",
                "Dyslexia",
                "Dysphagia",
                "Dyspraxia",
                "Dysthymic Disorder",
                "Dystonia",
                "Eating Disorder",
                "Ectodermal Dysplasia",
                "Ehlers-Danlos Syndrome",
                "Encephalitis",
                "Encephalopathy",
                "Endometriosis",
                "Eosinophilic Esophagitis",
                "Eosinophilic Fasciitis",
                "Epidermolysis Bullosa",
                "Epilepsy",
                "Epithelioid Sarcoma",
                "Erdheim-Chester Disease",
                "Erythromelalgia",
                "Erythropoietic Protoporphyria",
                "Esophageal Cancer",
                "Ewing Sarcoma",
                "Facial Paralysis",
                "Familial Adenomatous Polyposis",
                "Familial Dysautonomia",
                "Fanconi Anemia",
                "Femoral Acetabular Impingement",
                "Fibrodysplasia Ossificans Progressiva",
                "Fibromyalgia",
                "Fibrosing Mediastinitis",
                "Fibrous Dysplasia",
                "Food Protein-Induced Enterocolitis Syndrome (FPIES)",
                "Fragile X Syndrome",
                "Functional Neurological Disorder/Conversion Disorder",
                "Gastroesophageal Reflux Disease (GERD)",
                "Gastroparesis",
                "Gastroschisis",
                "Gaucher Disease",
                "Generalized Gangliosidoses",
                "Gestational Trophoblastic Disease",
                "Glaucoma",
                "Glutaric Acidemia",
                "Glycogen Storage Disease",
                "GM1 Gangliosidosis",
                "Goldenhar Syndrome",
                "Graft-Versus-Host Disease",
                "Granulomatosis with Polyangiitis (GPA)",
                "Graves' Disease",
                "GRIN2B",
                "Guillain-Barre Syndrome",
                "Hashimoto's Thyroiditis",
                "Helsmoortel-Van Der Aa Syndrome",
                "Hemangioma",
                "Hemicrania Continua",
                "Hemiplegic Migraine",
                "Hemolytic Anemia",
                "Hemophagocytic Lymphohistiocytosis",
                "Hemophilia",
                "Hereditary Angioedema",
                "Hereditary Diffuse Gastric Cancer",
                "Hereditary Neuropathies",
                "Hereditary Spastic Paraplegia",
                "Heterotaxy Syndrome",
                "Hidradenitis Suppurativa",
                "Hip Dysplasia",
                "Hirschsprung's Disease",
                "HIV/AIDS",
                "Hunter Syndrome",
                "Huntington's Disease",
                "Hurler Syndrome",
                "Hutchinson-Gilford Progeria Syndrome",
                "Hydrocephalus",
                "Hyper IGE Syndrome",
                "Hyperacusis",
                "Hyperemesis Gravidarum",
                "Hypersomnia",
                "Hypoglycemia",
                "Hypokalemic Periodic Paralysis",
                "Hypophosphatasia",
                "Hypoplastic Left Heart Syndrome",
                "Hypoplastic Right Heart Syndrome",
                "Hypothyroidism (Underactive Thyroid Disease)",
                "Hypotonia",
                "Hypoxic Ischemic Encephalopathy",
                "Ichthyosis" ,
                "Idic 15",
                "Idiopathic Angioedema",
                "Idiopathic Hypersomnia",
                "Idiopathic Intracranial Hypertension",
                "Idiopathic Thrombocytopenic Purpura (ITP)",
                "Inappropriate Sinus Tachycardia",
                "Inclusion Body Myositis",
                "Infantile Scoliosis",
                "Infantile Spasms",
                "Inflammatory Bowel Disease (IBD)",
                "Insomnia",
                "Interstitial Cystitis",
                "Intracranial Hypertension",
                "Irritable Bowel Syndrome (IBS)",
                "Ivemark Syndrome",
                "Joint Hypermobility Syndrome",
                "Joubert Syndrome",
                "Kabuki Syndrome",
                "Kallmann Syndrome",
                "Kidney Disease",
                "Klippel-Feil Syndrome",
                "Krabbe Disease",
                "L1 Syndrome",
                "Langerhans Cell Histiocystosis",
                "Laryngomalacia",
                "Lennox-Gastaut Syndrome",
                "Leukemia",
                "Leukodystrophy",
                "Limb Amputation",
                "Lipedema",
                "Lissencephaly",
                "Liver Cancer",
                "Liver Melanoma",
                "Locked-In Syndrome",
                "Long QT Syndrome",
                "Lung Cancer",
                "Lupus",
                "Lyme Disease",
                "Lymphedema",
                "Lymphoma",
                "Mal de Debarquement Syndrome (MdDS)",
                "Marfan Syndrome",
                "Mast Cell Activation Disorder",
                "McCune-Albright Syndrome",
                "Median Arcuate Ligament Syndrome (MALS)",
                "Melanoma",
                "Melkersson-Rosenthal Syndrome",
                "Meniere's Disease",
                "Meningitis",
                "Menkes Disease",
                "Mental Illness",
                "Mesothelioma",
                "Metachromatic Leukodystrophy",
                "Microcephaly",
                "Migraines",
                "Misophonia",
                "Mitochondrial Disease",
                "Mixed Connective Tissue Disease (MCTD)",
                "Moebius Syndrome",
                "Motor Neuron Diseases",
                "MTHFR Mutation",
                "Mucopolysaccharidoses",
                "Multiple Chemical Sensitivity",
                "Multiple Endocrine Neoplasia Type 2",
                "Multiple Hereditary Exostoses",
                "Multiple Myeloma",
                "Multiple Sclerosis",
                "Multiple System Atrophy",
                "Muscle Dysfunction",
                "Muscular Dystrophy",
                "Myalgic Encephalomyelitis/Chronic Fatigue Syndrome",
                "Myasthenia Gravis",
                "Myeloproliferative Neoplasms",
                "Myotonic Muscular Dystrophy",
                "Narcolepsy",
                "Nemaline Myopathy",
                "Nephrotic Syndrome",
                "Neuroblastoma",
                "Neurocardiogenic syncope",
                "Neuroendocrine Tumor",
                "Neurofibromatosis",
                "Neuropathy - Hereditary",
                "NGLY1 Deficiency",
                "Niemann-Pick Disease",
                "Noonan Syndrome",
                "Nystagmus",
                "Obsessive-Compulsive Disorder (OCD)",
                "Occipital Neuralgia",
                "Onychotillomania",
                "Osteogenesis Imperfecta",
                "Osteosarcoma",
                "Ovarian Cancer",
                "Pancreatic Cancer",
                "Panhypopituitarism",
                "PANS/PANDAS",
                "Parkes Weber Syndrome",
                "Parkinson's Disease",
                "Parsonage-Turner Syndrome",
                "Pelizaeus-Merzbacher Disease",
                "Periodic Fever, Aphthous Stomatitis, Pharyngitis, Cervical Adenitis (PFAPA)",
                "Periodic Paralysis",
                "Peripheral Neuropathy",
                "Peroxisomal Biogenesis Disorder",
                "Pervasive Developmental Disorders",
                "Phelan-McDermid Syndrome (22q13 Deletion Syndrome)",
                "Pitt-Hopkins Syndrome",
                "Pityriasis Lichenoides",
                "PMM2-CDG",
                "Polycystic Kidney Disease",
                "Polycystic Ovary Syndrome (PCOS)",
                "Polymicrogyria",
                "Polymyositis",
                "Pompe Disease",
                "Post-traumatic Stress Disorder (PTSD)",
                "Postural Orthostatic Tachycardia Syndrome",
                "Prader-Willi Syndrome",
                "Preeclampsia",
                "Prematurity",
                "Premenstrual Dysphoric Disorder",
                "Primary Immunodeficiency",
                "Prinzmetal Angina",
                "Progeria",
                "Progressive Supranuclear Palsy",
                "Propionic Acidemia",
                "Prostate Cancer",
                "Prune Belly Syndrome",
                "Pseudomyxoma Peritonei",
                "Psoriasis",
                "Psoriatic Arthritis",
                "Pudendal Neuralgia",
                "Pulmonary Arterial Hypertension",
                "Pulmonary Embolism",
                "Pulmonary Hypertension",
                "Rare Disease",
                "Raynauds Phenomenon",
                "Reactive Attachment Disorder",
                "Reflex Sympathetic Dystrophy Syndrome",
                "Relapsing Polychondritis",
                "Renal Tubular Acidosis",
                "Restless Legs Syndrome",
                "Retinitis Pigmentosa",
                "Retinoblastoma",
                "Rett Syndrome",
                "Rhabdomyosarcoma",
                "Rhizomelic Chondrodysplasia Punctata",
                "Ring 22 Syndrome",
                "Rosacea",
                "Rubinstein-Taybi Syndrome",
                "Saethre-Chotzen Syndrome",
                "Sanfilippo Syndrome",
                "Sarcoidosis",
                "SATB2-Associated Syndrome",
                "Schizoaffective Disorder",
                "Schizophrenia",
                "Schwartz-Jampel Syndrome",
                "Scimitar Syndrome",
                "Scleroderma",
                "Scoliosis",
                "Seizure Disorder",
                "Sensory Processing Disorder",
                "Septo-Optic Dysplasia",
                "Severe Combined Immunodeficiency (SCID)",
                "Short Bowel Syndrome",
                "Shwachman Diamond Syndrome (SDS)",
                "Sickle Cell Disease",
                "Sinus Tachycardia",
                "Sjögren's Syndrome",
                "Skeletal Dysplasia",
                "Skin Cancer",
                "Smith-Lemli-Opitz Syndrome",
                "Smith-Magenis syndrome",
                "Snyder-Robinson Syndrome",
                "Sotos Syndrome",
                "Sphincter of Oddi Dysfunction",
                "Spina Bifida",
                "Spinal Cord Injury",
                "Spinal Muscular Atrophy",
                "Spinal Stenosis",
                "STAT 1 Deficiency",
                "Stevens-Johnson Syndrome",
                "Stickler Syndrome/ Pierre-Robin Stickler Syndrome",
                "Stomach Cancer",
                "Stroke",
                "Sturge-Weber Syndrome",
                "Superior Mesenteric Artery Syndrome",
                "Superior Semicircular Canal Dehiscence Syndrome",
                "Syringomyelia",
                "Systemic Sclerosis",
                "Takayasu's Arteritis",
                "Tardive Dyskinesia",
                "Tay-Sachs Disease",
                "Testicular Cancer",
                "Tethered Spinal Cord Syndrome",
                "Thoracic Outlet Syndrome",
                "Thyroid Cancer",
                "Tourette Syndrome",
                "Tracheomalacia",
                "Transverse Myelitis",
                "Traumatic Brain Injury",
                "Treacher Collins Syndrome (TCS)",
                "Trichotillomania",
                "Tricuspid Atresia",
                "Trigeminal Neuralgia",
                "Trisomy 18/Edwards' Syndrome",
                "Trisomy 5q",
                "Truncus Arteriosus",
                "Tuberous Sclerosis Complex",
                "Turner Syndrome",
                "Type I, II, & III Autoimmune Polyglandular Syndromes",
                "Ulcerative Colitis",
                "Urea Cycle Disorder",
                "Usher Syndrome",
                "Uveitis",
                "VACTERL",
                "Vasculitis",
                "Vertebral Artery Dissection",
                "Vitiligo",
                "Vocal cord dysfunction",
                "Von Hippel-Lindau Syndrome (VHL)",
                "Von Willebrand Disease",
                "Warburg Micro syndrome",
                "White Matter Brain Disorder",
                "Williams Syndrome",
                "Undiagnosed",
                "Other"]

let interests = ["Animals",
                 "Arts & Humanities",
                 "Books & Literature",
                 "Beauty & Personal Care",
                 "Cars",
                 "Computers & Electronics",
                 "Entertainment (TV, Movies, Celebrities, etc.",
                 "Food",
                 "Games",
                 "Music",
                 "News & Current Events",
                 "Photo & Video",
                 "Science",
                 "Shopping",
                 "Sports",
                 "Travel",
                 "Other"]
